/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bsamuel.exercise.string;

import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

public class CountingDuplicateCharacters {

	public static void main(String[] args) {
		
		CountingDuplicateCharacters cDC = new CountingDuplicateCharacters();
		Map result1 = cDC.countDuplicateCharacters1("Hello World");
		Map result2 = cDC.countDuplicateCharacters2("James Camden");
		
		System.out.println(result1);
		System.out.println(result2);
		
		
	}
	
	public Map<Character, Integer> countDuplicateCharacters1 (String str) {
		
		Map<Character, Integer> result = new HashMap<> ();
		
		for (int i = 0; i<str.length(); i++) {
			char ch = str.charAt(i);
			result.compute(ch, (k, v) -> (v == null) ? 1 : ++v);
		}
		return result;
	}
	
	public Map<Character, Long> countDuplicateCharacters2(String str) {
		
		Map<Character, Long> result = str.chars()
				.mapToObj(c -> (char) c)
				.collect(Collectors.groupingBy(c -> c, Collectors.counting()));
				
		return result;		
		
		
	}
	
	
}
